export const setup = {
  name: "KennyBookStore",
  border: "#3e5962",
  inside: "#cf5b5b",
  color: "white",
  banner: "/assets/images/banner.jpg",
  error: "rgb(211, 47, 47)",
  success: "rgb(46, 125, 50)",
  email: "cskg.kennybookstore@gmail.com",
  backgroundColor: "white",
  address: "46/37C Nhiêu Tứ, Phường 07, Quận Phú Nhuận, Hồ Chí Minh"
};


export const suggest = [
  "Mèo Mốc Black Book – tập 1",
"Mèo Mốc Black Book - tập 2",
"Mèo Mốc Black Book - tập 3",
"Mèo Mốc Black Book - tập 4",
"Mèo Mốc: Ơ, Sinh Nhật Rồi Này?",
"TonTon Friends - Hội Chân Ngắn Siêu Lầy",
"Những Con Mèo Ở Tử Cấm Thành (Tập 1)",
"Những Con Mèo Ở Tử Cấm Thành (Tập 2)",
"Combo 11 Tập: Người Bà Tài Giỏi Vùng Saga",
"Truyện tranh - Trọn bộ 23 cuốn: Doraemon bóng chày",
"Án Mạng Mười Một Chữ",
"Bão Ngầm",
"Hannibal",
"Sherlock Holmes Toàn Tập",
"Phố Tan Màn Đêm - Higashino Keigo",
"Nỗi Niềm Của Thám Tử Galileo",
"Thảm Án Lúc Nửa Đêm",
"Truyện trinh thám : Ảo Dạ",
"Lời nhắn cuối cùng",
"Dữ Liệu Bạch Kim",
"Nhà Giả Kim (Tái Bản 2020)",
"Đại gia Gatsby - Bìa cứng",
"Túp Lều Của Bác Tom (Tái Bản 2018)",
"Nhà Thờ Đức Bà Paris (Bìa Cứng)",
"Những Tấm Lòng Cao Cả (Bìa Cứng)",
"Kiêu hãnh và định kiến (bìa cứng)",
"Tam Quốc chí (Boxset trọn bộ 5 tập)",
"Ông già và biển cả",
"Faust - Johann WolfGang Von Goethe",
"Nhật Ký Trong Tù",
"BÓNG MA TRÊN PHỐ GINZA",
"Người Phát Ngôn Của Thần Chết",
"Những Con Quái Vật Đội Lốt Người Trong Thị Trấn",
"Combo 2 Cuốn Gã Hề Ma Quái",
"Goth - Những Kẻ Hắc Ám",
"Lò Mổ Linh Hồn",
"Lời Hứa Của Bóng Đêm",
"Ma Quỷ Dân Gian Ký",
"Những Chuyện Kỳ Bí Trong Ngõ Hẹp",
"Truyện kinh dị Việt Nam - Thần hổ",
];
export const priceList = [
  {
    id: 0,
    name: "< 50,000",
  },
  {
    id: 1,
    name: "50,000 - 200,000",
  },
  {
    id: 2,
    name: "200,000 - 500,000",
  },
  {
    id: 3,
    name: "500,000 - 800,000",
  },
];
